### ISSUE TITLE
Integration to "Twelve Monkeys"

### ISSUE THREAD

**Issue by HermannKroll** [rii-mango/JPEGLosslessDecoder#1]
Hallo,

nice library. After a couple of hours searched i found this library to decode JPEG Lossless files. My task was to do a own implementation for JPEG Lossless parsing for DICOM files. This code should be contributed to the "TwelveMonkeys" ImageLibrary, which we use in our DICOM Software. 
(Github Link for "TwelveMonkeys")

Maybe there is a possibility to integrate your Code into the "TwelveMonkeys" Project? If you want, I can do the implementation. I know you use the MIT license, but i wanted to hear, if its okay for you.

Best regards
Hermann

**Comment by rii-mango** [comment]
Sounds fine with me.  Helmet Dersch's library was originally LGPL, but I recently asked him if we could change to MIT, which he agreed.  My contribution was to add support for selection values 2 through 7 as well as bug fixes.  There's also a JavaScript port here: https://github.com/rii-mango/JPEGLosslessDecoderJS
