### ISSUE TITLE
JPEG Lossless, some values exceed the the precision range

### ISSUE THREAD

**Issue by HermannKroll** [rii-mango/JPEGLosslessDecoder#2]
Hello,

I've got a problem. I have JPEG Lossless images with 16 bit precision and 1 component (your library and the DICOM information tells me that) 

```
    try {
        //read in test
        FileInputStream inStream = new FileInputStream("test0.pixeldata");
        int avaibleBytes = inStream.available();
        byte[] data = new byte[avaibleBytes];
        inStream.read(data);
        //create decoder here
        JPEGLosslessDecoder decoder = new JPEGLosslessDecoder(data);
        int[][] decoded = decoder.decode();

        // added getFrameHeader in JPEGLosslessDecoder for this prints here
        FrameHeader header = decoder.getFrameHeader();
        System.out.println("Components: " + header.getNumComponents());
        System.out.println("Precision : " + header.getPrecision());


        int min = Integer.MAX_VALUE;
        int max = Integer.MIN_VALUE;
        for(int i = 0; i < decoded[0].length; i++){
            if(min > decoded[0][i]){
                min = decoded[0][i];
            }
            if(max < decoded[0][i]){
                max = decoded[0][i];
            }
        }
        System.out.println("Max value: " + max);
        System.out.println("Min value: " + min);


    } catch(Exception ex){
        ex.printStackTrace();
    }
```

The console output is:
Components: 1
Precision : 16
Max value: 67007
Min value: 63536

Why does some values exceeds the range of 16 bit precision? I assumed that the values could be wrapped safely by an Java short.

I attached you the image stream from a DICOM file saved to an .pixeldata - file in a .zip.

Best regards & Thanks
Hermann

[test0.pixeldata.zip](https://github.com/rii-mango/JPEGLosslessDecoder/files/61515/test0.pixeldata.zip)

**Comment by rii-mango** [comment]
Is it possible to send the DICOM file (or a de-identified version of it if necessary)?

**Comment by HermannKroll** [comment]
Hi,

here are the first three images from the dicom series.

Best regards
Hermann

[Dicom JPEG Lossless Anonym.zip](https://github.com/rii-mango/JPEGLosslessDecoder/files/62507/Dicom.JPEG.Lossless.Anonym.zip)

**Comment by rii-mango** [comment]
Try again.  It should be fixed now.  The data needed to be masked.  I was masking the output of this decoder in other code, but it makes more sense to mask within the decoder itself.

**Comment by HermannKroll** [comment]
Thanks, seems to work now. 
Last question:
Currently I write a wrapper for your library to put the decoded data into BufferedImages. Do you want to integrate this into your library? (If yes, i will create a pull request in the next days)

**Comment by rii-mango** [comment]
Yes, please do send the pull request.  Thanks!
