### ISSUE TITLE
Format of decompressed bytes?

### ISSUE THREAD

**Issue by gkjpettet** [rii-mango/JPEGLosslessDecoder#6]
Hi. Firstly, thank so much for writing this. I'm writing a DICOM parser in a different language (Xojo) and, like many people, managed to read the elements in the DICOM file and be able to generate an image if the PixelData was uncompressed but have struggled to decode lossless JPEG.

I'm attempting to port this Java library to Xojo. I have one question. In the readme it says:

> // single component
int[] decompressedData = decoder.decode()[0]; 

The bytes in `decompressedData` what format are they? Can I consider them the same as if they were in DICOM's "uncompressed" format. I.e I just need to apply `RescaleSlope` and `RescaleIntercept` and windowing to them or have they been decoded to a different JPEG format?

**Comment by rii-mango** [comment]
@gkjpettet That would be the raw DICOM pixel data -- yes, appropriate for rescale/window -- not in any JPEG format.  Sorry the late reply.

**Comment by gkjpettet** [comment]
Thank you.
